package com.raeyncreations.raeyncheat.auth;

import com.raeyncreations.raeyncheat.RaeYNCheat;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.ByteBuffer;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.Collections;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * RFC 6238 TOTP (Time-based One-Time Password) implementation.
 *
 * Pure Java — zero external dependencies. Compatible with every major
 * authenticator app: Microsoft Authenticator, Google Authenticator, Authy,
 * Bitwarden, 1Password, etc.
 *
 * Algorithm:
 *   1. secret = 20-byte random key, Base32-encoded for QR code
 *   2. T = floor(unix_epoch_seconds / 30)  — current 30-second time step
 *   3. HMAC-SHA1(secret_bytes, T_as_8_byte_big_endian)
 *   4. Dynamic truncation → 4 bytes → 6-digit code
 *
 * Window tolerance: ±1 step (±30s) to account for clock drift and slow typists.
 * This is industry standard (RFC 6238 §5.2 recommends ±1).
 *
 * Secret storage: The raw Base32 secret is what we store in the database
 * (encrypted at rest by AuthDatabase). The URI generated by buildProvisioningUri()
 * is what goes into a QR code for the player to scan.
 */
public class TotpUtil {

    private static final int    SECRET_BYTES    = 20;    // 160 bits — standard TOTP secret size
    private static final int    CODE_DIGITS     = 6;
    private static final int    STEP_SECONDS    = 30;
    private static final int    WINDOW_TOLERANCE = 1;    // ±1 step = ±30 seconds
    private static final long   DIGIT_POWER     = 1_000_000L; // 10^6 for 6-digit codes
    private static final String HMAC_ALGORITHM  = "HmacSHA1";

    private static final SecureRandom SECURE_RANDOM = new SecureRandom();

    /**
     * Persistent replay protection backed by AuthDatabase.
     * The DB is injected at server startup via TotpUtil.setDatabase().
     * Falls back to the in-memory set when no DB is available (unit tests, client side).
     *
     * On a server restart, the DB still contains all recent replay keys, so a just-used
     * TOTP code remains rejected even after a crash+restart within the 2-minute window.
     */
    private static volatile AuthDatabase replayDb = null;

    /** Inject the database for persistent replay protection. Call once at server startup. */
    public static void setDatabase(AuthDatabase db) {
        replayDb = db;
    }

    // In-memory fallback for contexts where no DB is available (client-side, tests).
    private static final Set<String> USED_CODES  = Collections.synchronizedSet(new HashSet<>());
    private static final java.util.concurrent.ConcurrentHashMap<String, Long> CODE_EXPIRY
            = new java.util.concurrent.ConcurrentHashMap<>();
    private static final int REPLAY_WINDOW_STEPS = 4; // expire entries after 4 steps (~2 min)

    // Base32 alphabet (RFC 4648)
    private static final String BASE32_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";

    // ---------------------------------------------------------------------------
    // Secret generation
    // ---------------------------------------------------------------------------

    /**
     * Generate a new random TOTP secret.
     * Returns the Base32-encoded string that players enter into their authenticator app.
     */
    public static String generateSecret() {
        byte[] secretBytes = new byte[SECRET_BYTES];
        SECURE_RANDOM.nextBytes(secretBytes);
        return base32Encode(secretBytes);
    }

    // ---------------------------------------------------------------------------
    // Code generation and verification
    // ---------------------------------------------------------------------------

    /**
     * Verify a 6-digit TOTP code against a Base32 secret.
     * Checks current time step plus ±WINDOW_TOLERANCE steps for clock drift tolerance.
     *
     * @param secret   Base32-encoded secret (as stored in DB / shown in QR)
     * @param code     6-digit code from player's authenticator app
     * @return true if the code is valid for the current time window
     */
    /**
     * Verify a 6-digit TOTP code against a Base32 secret.
     * Includes replay protection: a code that has already been successfully used within
     * the tolerance window is rejected, preventing the same OTP from being submitted twice
     * (e.g. by network replay or a player sharing their code).
     *
     * @param secret    Base32-encoded secret
     * @param code      6-digit code from the authenticator app
     * @param playerUuid Player UUID string — used to scope replay protection per-player
     * @return true if the code is valid and has not been used before
     */
    public static boolean verifyCode(String secret, String code, String playerUuid) {
        if (secret == null || code == null || playerUuid == null) return false;
        code = code.trim().replaceAll("\\s", "");
        if (code.length() != CODE_DIGITS) return false;

        int inputCode;
        try {
            inputCode = Integer.parseInt(code);
        } catch (NumberFormatException e) {
            return false;
        }

        byte[] secretBytes;
        try {
            secretBytes = base32Decode(secret.toUpperCase().trim());
        } catch (Exception e) {
            return false;
        }

        long currentStep = System.currentTimeMillis() / 1000L / STEP_SECONDS;

        cleanupExpiredCodes(currentStep);

        for (int delta = -WINDOW_TOLERANCE; delta <= WINDOW_TOLERANCE; delta++) {
            try {
                long step = currentStep + delta;
                int expected = generateCode(secretBytes, step);
                if (expected == inputCode) {
                    String replayKey = playerUuid + ":" + step + ":" + inputCode;
                    long expiresAtStep = currentStep + REPLAY_WINDOW_STEPS;

                    AuthDatabase db = replayDb;
                    if (db != null) {
                        // DB path: INSERT OR IGNORE is atomic — returns false if key exists (replay).
                        try {
                            boolean inserted = db.markTotpCodeUsed(replayKey, expiresAtStep);
                            if (!inserted) return false; // replay detected via DB
                        } catch (Exception e) {
                            // DB failure — fall back to in-memory check rather than blocking auth.
                            RaeYNCheat.LOGGER.warn("[TotpUtil] DB replay check failed, using in-memory fallback: {}", e.getMessage());
                            if (USED_CODES.contains(replayKey)) return false;
                            USED_CODES.add(replayKey);
                            CODE_EXPIRY.put(replayKey, expiresAtStep);
                        }
                    } else {
                        // No DB (client/test context): in-memory only.
                        if (USED_CODES.contains(replayKey)) return false;
                        USED_CODES.add(replayKey);
                        CODE_EXPIRY.put(replayKey, expiresAtStep);
                    }
                    return true;
                }
            } catch (Exception ignored) {}
        }
        return false;
    }

    /**
     * Overload without UUID — for use in setup confirmation where UUID is implicit.
     * Uses a placeholder UUID so the signature is consistent.
     */
    public static boolean verifyCode(String secret, String code) {
        return verifyCode(secret, code, "SETUP");
    }

    /** Remove expired entries from the used-codes set. Called on every verification. */
    private static void cleanupExpiredCodes(long currentStep) {
        Iterator<java.util.Map.Entry<String, Long>> it = CODE_EXPIRY.entrySet().iterator();
        while (it.hasNext()) {
            java.util.Map.Entry<String, Long> entry = it.next();
            if (entry.getValue() <= currentStep) {
                USED_CODES.remove(entry.getKey());
                it.remove();
            }
        }
    }

    /**
     * Generate the TOTP code for a given time step.
     * Exposed for testing. Use verifyCode() in production.
     */
    public static int generateCode(byte[] secretBytes, long timeStep) throws Exception {
        byte[] stepBytes = ByteBuffer.allocate(8).putLong(timeStep).array();
        byte[] hash = hmacSha1(secretBytes, stepBytes);

        // Dynamic truncation (RFC 4226 §5.4)
        int offset = hash[hash.length - 1] & 0x0F;
        int truncated = ((hash[offset]     & 0x7F) << 24)
                      | ((hash[offset + 1] & 0xFF) << 16)
                      | ((hash[offset + 2] & 0xFF) << 8)
                      |  (hash[offset + 3] & 0xFF);

        return (int)(truncated % DIGIT_POWER);
    }

    // ---------------------------------------------------------------------------
    // Provisioning URI (for QR code display in chat)
    // ---------------------------------------------------------------------------

    /**
     * Build the otpauth:// URI that authenticator apps parse when scanning a QR code.
     * Since we're in Minecraft chat (no image rendering), we display the URI as text
     * and the player enters the secret manually into their app.
     *
     * Format: otpauth://totp/LABEL?secret=SECRET&issuer=ISSUER&algorithm=SHA1&digits=6&period=30
     *
     * @param playerName  Minecraft username (displayed as account label in the app)
     * @param secret      Base32 TOTP secret
     * @param issuer      App/server name shown in the authenticator (e.g. "RaeYNServer")
     */
    public static String buildProvisioningUri(String playerName, String secret, String issuer) {
        String label = urlEncode(issuer + ":" + playerName);
        return "otpauth://totp/" + label
                + "?secret=" + secret.replace(" ", "")
                + "&issuer=" + urlEncode(issuer)
                + "&algorithm=SHA1&digits=6&period=30";
    }

    // ---------------------------------------------------------------------------
    // HMAC-SHA1
    // ---------------------------------------------------------------------------

    private static byte[] hmacSha1(byte[] key, byte[] data)
            throws NoSuchAlgorithmException, InvalidKeyException {
        Mac mac = Mac.getInstance(HMAC_ALGORITHM);
        mac.init(new SecretKeySpec(key, HMAC_ALGORITHM));
        return mac.doFinal(data);
    }

    // ---------------------------------------------------------------------------
    // Base32 encode/decode (RFC 4648, no padding issues)
    // ---------------------------------------------------------------------------

    public static String base32Encode(byte[] data) {
        StringBuilder sb = new StringBuilder();
        int buffer = 0, bitsLeft = 0;
        for (byte b : data) {
            buffer = (buffer << 8) | (b & 0xFF);
            bitsLeft += 8;
            while (bitsLeft >= 5) {
                bitsLeft -= 5;
                sb.append(BASE32_CHARS.charAt((buffer >> bitsLeft) & 0x1F));
            }
        }
        if (bitsLeft > 0) {
            buffer <<= (5 - bitsLeft);
            sb.append(BASE32_CHARS.charAt(buffer & 0x1F));
        }
        return sb.toString();
    }

    public static byte[] base32Decode(String input) {
        input = input.toUpperCase().replaceAll("[^A-Z2-7]", "");
        byte[] output = new byte[input.length() * 5 / 8];
        int buffer = 0, bitsLeft = 0, index = 0;
        for (char c : input.toCharArray()) {
            int val = BASE32_CHARS.indexOf(c);
            if (val < 0) continue;
            buffer = (buffer << 5) | val;
            bitsLeft += 5;
            if (bitsLeft >= 8) {
                bitsLeft -= 8;
                output[index++] = (byte)(buffer >> bitsLeft);
            }
        }
        return index < output.length ? java.util.Arrays.copyOf(output, index) : output;
    }

    // ---------------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------------

    private static String urlEncode(String s) {
        try {
            return java.net.URLEncoder.encode(s, "UTF-8").replace("+", "%20");
        } catch (Exception e) {
            return s;
        }
    }

    /**
     * Format a Base32 secret in groups of 4 for human readability.
     * Example: "JBSWY3DPEHPK3PXP" → "JBSW Y3DP EHPK 3PXP"
     */
    public static String formatForDisplay(String secret) {
        if (secret == null) return "";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < secret.length(); i++) {
            if (i > 0 && i % 4 == 0) sb.append(' ');
            sb.append(secret.charAt(i));
        }
        return sb.toString();
    }
}
